### ISSUE TITLE
Switch to a different UI framework

### ISSUE THREAD

**Issue by terenceponce** [obudget/ui#21]
In the blog post that I wrote for [UI's v0.1.0 release](https://medium.com/openbudget/openbudget-ui-v0-1-0-225ebc8f029e), I mentioned that I struggled a lot when I was trying to add tests for this project.

What happens is that Material UI adds their `withStyle` HOC to every component in the application. This makes it very complicated to even do some simple assertions when it comes to tests.

At first, I thought it was something that I could live with, but thinking about it more has gotten me irritated over this topic. I know a lot of people think automated testing isn't really that important when it comes to front end development, but I really want to do tests the right way for this project.

Despite my fondness of Material UI, I think this is a deal breaker. Even if it would take longer, I think switching the UI framework would be the better move in the long term.

With that said, here are the things that I think are important when choosing another UI framework:

- The UI framework should not get in the way of testing (This is the most important).
- It should play well with [styled-components](https://www.styled-components.com). I tried doing this with Material UI, but it ended up not working for the most part. MUI looks to be deeply rooted in JSS at this point.
- The generated HTML of the UI framework's components should be predictable and easy to read. One of my goals for Open Budget is for the code base to be simple enough for beginners to pick up and contribute to.
- It should look good out of the box without customizations.
- Lastly, it should support theming to some extent. I'm not a designer, but I think theme support will be valuable at some point.

I did a bit of research and I think [Semantic UI React](https://react.semantic-ui.com/) is the best candidate for this. It passes most of the checks that I have although I'm still not sure about the testing part.

I'm open to suggestions and I'll also do some more research on this, but I think this project will end up adopting Semantic UI React if no other compelling arguments come up.

I also wrote this issue on our blog: https://medium.com/openbudget/switching-to-a-different-ui-framework-a6fdf2d1a053

**Comment by terenceponce** [comment]
Work for this issue has already started in this branch: https://github.com/obudget/ui/tree/ui-framework-switch

So far, I think it's working out fine. Semantic UI is definitely not getting in the way of testing, so it's got that going for it.

I did encounter an issue when installing the whole Semantic UI package because the way it sets up its directories clashes with `create-react-app`'s rules. Specifically, its rule against doing any relative imports outside of the `src/` directory. I asked what the solution should be in [this issue thread](https://github.com/Semantic-Org/Semantic-UI-React/issues/1330#issuecomment-340265335), but I'm not getting any answers so far.

We definitely need to resolve that aspect because we want the theming capabilities of Semantic UI.

**Comment by mojave27** [comment]
@terenceponce How did you work around the ../semantic/dist issue for importing the semantic-ui-css?  I ran into the same issue you referenced in the semantic-ui issue.

**Comment by terenceponce** [comment]
@mojave27 If you look at the file directory, I placed the whole semantic-ui folder inside `src` and I changed `semantic.json` to look at that directory instead. You can see it [here](https://github.com/obudget/web/blob/master/semantic.json).
